baseURL = 'https://harshitv804.github.io'
languageCode = 'en-us'
title = 'Harshit V'
theme = 'archie'
copyright = "© Harshit V"

[params]
	mode="toggle"
  useCDN=false
  favicon = "https://github.com/harshitv804/harshitv804.github.io/assets/100853494/189607e5-37f5-4045-ba29-f9d0bd6c5d52"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[menu.main]]
name = "OpenGPT"
url = "/opengpt"
weight = 4

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5